name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=Swiggy
            -Dsonar.projectName=Swiggy
            -Dsonar.sources=.

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Docker build and push to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 950933358440.dkr.ecr.us-east-1.amazonaws.com
          docker build -t pratikshyap -f deployment-using-github-actions/Dockerfile deployment-using-github-actions/
          docker tag pratikshyap:latest 950933358440.dkr.ecr.us-east-1.amazonaws.com/pratikshyap:latest
          docker push 950933358440.dkr.ecr.us-east-1.amazonaws.com/pratikshyap:latest

  deploy:
    name: Deploy
    needs: build
    runs-on: [self-hosted]

    steps:
      - name: Docker pull image
        run: docker pull 950933358440.dkr.ecr.us-east-1.amazonaws.com/pratikshyap:latest

      - name: Image scan
        run: trivy image 950933358440.dkr.ecr.us-east-1.amazonaws.com/pratikshyap:latest

      - name: Deploy to container
        run: docker run -d --name swiggy-clone -p 3000:3000 950933358440.dkr.ecr.us-east-1.amazonaws.com/pratikshyap:latest
